### PR TITLE
add Typescript definitions

### PR DESCRIPTION
**Pull request by Athou**
This pull request adds Typescript definitions for the library so that it's usable in a type-safe way.

### CODE REVIEW

**Comment by nathanbuchar** [comment]
I'll be honest, I don't have a clue what I'm looking at here, but I added it to `react-hook-thunk-reducer@next`. Give it a shot and let me know if it looks good to release :)

**Comment by Athou** [comment]
Haha thanks!
I know it looks a little bit complicated but it's actually not.

I'm not sure how to test though :(
I cloned the repo, ran `npm install` and `npm run build` and then changed my package.json (https://github.com/Athou/commafeed-ui/) to add `"react-hook-thunk-reducer": "file:../react-hook-thunk-reducer"`. I then deleted `src/thunk-reducer.ts` and changed the imports from App.tsx to use your package.
Is this the right approach? Because I get the following error and I'm not sure how to fix it:

    TypeError: Object(...) is not a function
    App
    P:/commafeed-ui/src/app/App.tsx:34

    31 | 
    32 | export const AppContext = React.createContext({} as { state: State; dispatch: Dispatch<Actions | Thunk<State, Actions>> })
    33 | 
    > 34 | export const App: React.FC<RouteComponentProps> = props => {
    35 |     const [state, dispatch] = useThunkReducer<State, Actions>(AppReducer, {
    36 |         tree: {},
    37 |         entries: { loading: false },

image

Thanks for your help.

**Comment by nathanbuchar** [comment]
You don't need to clone the repo, just run `npm install react-hook-thunk-reducer@next` and it will install the beta version :)

Let me know if that works, if not I can take a deeper look!

**Comment by Athou** [comment]
Oh alright, thanks that's much simpler.

I get the same error as before but it seems I missed that useThunkReducer is actually the default export (this comment made me realize what was the problem https://github.com/facebook/react/issues/14484#issuecomment-497504516)

I'll submit a PR :)

**Pull request closed without merging**
